# Generated by Django 3.2.4 on 2023-05-08 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="../default_post_rgq6aq",
                        upload_to="images/",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("0", "Educational"),
                            ("1", "Cultural"),
                            ("2", "Recreational"),
                            ("3", "Fundraiser"),
                            ("4", "Private"),
                            ("5", "Work"),
                            ("6", "Exhibition"),
                            ("7", "Festival"),
                            ("8", "Concert"),
                            ("9", "Cinema"),
                            ("10", "Party"),
                            ("11", "Seminar"),
                            ("11", "Personal"),
                            ("13", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.URLField()),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("0", "Public"),
                            ("1", "Followers only"),
                            ("2", "Private"),
                        ],
                        max_length=100,
                    ),
                ),
                ("past", models.BooleanField(null=True)),
                ("notification", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("all_day", models.BooleanField()),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time",
                        to="app_event.event",
                    ),
                ),
            ],
        ),
    ]
