# Generated by Django 3.2.4 on 2023-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2023-05-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventTime',
        ),
    ]
