# Generated by Django 3.2.4 on 2023-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_memory", "0003_alter_memory_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="plan",
            field=models.BooleanField(default=True),
        ),
    ]
